GET http://localhost:5138

###

GET http://localhost:5138/games

###

GET http://localhost:5138/games/3

###
POST http://localhost:5138/games
Content-Type: application/json

{
    "name": "Double Dragon IV",
    "genreId": "3",
    "price": 15.99,
    "releaseDate": "2004-02-01"
}

###

PUT http://localhost:5138/games/2
Content-Type: application/json

{
    "name": "The Red Dead Redemption 2",
    "genreId": 2,
    "price": 89.99,
    "releaseDate": "2022-05-12"
}

###
DELETE http://localhost:5138/games/3